### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jad-darrous** [Spirals-Team/docker-machine-driver-g5k#16]
Hello,

I have been using this driver for "long" time and everything is fine ! But from time to time I got this error message `"Post https://api.grid5000.fr/stable/sites/lyon/jobs: x509: certificate signed by unknown authority"`. If I repeated the action, it could disappear. This error could be really annoying if it happens inside a script.

I'm not sure if it is a problem related to the g5k-driver or g5k itself or my machine !

I'm running MacOSX, and I'm using Tunnelblick as VPN client.

Thanks in advance for any help.

**Comment by gfieni** [comment]
Hello, thanks for your feedback !
I can't reproduce this error, did you got it recently ?
Do you run Docker Machine with the driver on your MacOS machine or the frontend of the site ?

**Comment by jad-darrous** [comment]
I'm running the Docker Machine from my machine not the frontend.

The main problem with this error that it is not reproducible!  For example, it could happen for some machine in this for loop:

```
  for i in $(seq $nb_peers); do
    docker-machine create -d g5k \
      --g5k-resource-properties "cluster='sagittaire'" \
      --g5k-image "jessie-x64-nfs" \
      --g5k-walltime "1:30:00" \
      node-$i
  done
```

It appears usually in for loops, or if I'm running a series of commands in a script, ex:

```
i=1
docker-machine ssh node-$i 'docker load -i /home/jaddarrous/docker/images/nitro-alpine.tar.gz'
docker-machine ssh node-$i 'docker load -i /home/jaddarrous/docker/images/redis-alpine.tar.gz'
docker-machine ssh node-$i 'docker load -i /home/jaddarrous/docker/images/rabbitmq-3-alpine.tar.gz'
```

It could happens on the second command, while executing the first and the third ones without any problem.

**Comment by gfieni** [comment]
Hello,
I tried to reproduce the bug with a script making multiple sequential requests for 5 days, but it was unsuccessful.
This error don't come from Docker Machine, the driver or Grid'5000. Its related to your network/computer.

**Comment by jad-darrous** [comment]
OK, thanks. I'll see if I can figure out the problem.
