### ISSUE TITLE
Run docker from the frontend

### ISSUE THREAD

**Issue by jad-darrous** [Spirals-Team/docker-machine-driver-g5k#17]
Hello,

I'd like to run my experiments from the frontend. docker-machine is installed on the frontend but docker is not! I can provision machines but I cannot run docker containers on them. Users cannot install new softwares on the frontend, so, is there a solution?

Thanks,

**Comment by gfieni** [comment]
Hello,
The only solution is to use `docker-machine ssh machineName docker run ...` to control the Docker daemon of the node.

**Comment by jad-darrous** [comment]
OK, thank you a lot. I was trying with the conventional way of `eval "$(docker-machine env ....)"`
