### ISSUE TITLE
EOF bug in mac 

### ISSUE THREAD

**Issue by chakib-belgaid** [Spirals-Team/docker-machine-driver-g5k#35]
With the version 2.1 after the creation of the job and when i try to access to the machine it will generate an EOF error 
<img width="666" alt="image" src="https://user-images.githubusercontent.com/6245915/67571080-5bf9c880-f733-11e9-9925-13bbe89ff735.png">

**Comment by gfieni** [comment]
Which version of docker-machine do you use ?
Can you retry the command with debug mode enabled (`dm -D ls`) and post the detailed output ?

Thanks
